Added support for command parsing

diff --git a/sshrc b/sshrc
--- a/sshrc
+++ b/sshrc
@@ -11,11 +11,18 @@ function sshrc() {
             echo >&2 $'.sshrc.d and .sshrc files must be less than 64kb\ncurrent size: '$SIZE' bytes'
             exit 1
         fi
-        ssh -t "$@" "
+        if [ -z "$CMDARG" ]; then
+            WELCOME_MSG="
+                if [ -e /etc/motd ]; then cat /etc/motd; fi
+                if [ -e /etc/update-motd.d ]; then run-parts /etc/update-motd.d/ 2>/dev/null; fi
+                last -F \$USER 2>/dev/null | grep -v 'still logged in' | head -n1 | awk '{print \"Last login:\",\$4,\$5,\$6,\$7,\$8,\"from\",\$3;}'
+                "
+        else
+            WELCOME_MSG=""
+        fi
+        ssh -t "$DOMAIN" $SSHARGS "
             command -v openssl >/dev/null 2>&1 || { echo >&2 \"sshrc requires openssl to be installed on the server, but it's not. Aborting.\"; exit 1; }
-            if [ -e /etc/motd ]; then cat /etc/motd; fi
-            if [ -e /etc/update-motd.d ]; then run-parts /etc/update-motd.d/ 2>/dev/null; fi
-            last -F \$USER 2>/dev/null | grep -v 'still logged in' | head -n1 | awk '{print \"Last login:\",\$4,\$5,\$6,\$7,\$8,\"from\",\$3;}'
+            $WELCOME_MSG
             export SSHHOME=\$(mktemp -d -t .$(whoami).sshrc.XXXX)
             export SSHRCCLEANUP=\$SSHHOME
             trap \"rm -rf \$SSHRCCLEANUP; exit\" 0
@@ -50,6 +57,7 @@ EOF
 
             echo $'"$(tar czf - -h -C $SSHHOME $files | openssl enc -base64)"' | tr -s ' ' $'\n' | openssl enc -base64 -d | tar mxzf - -C \$SSHHOME
             export SSHHOME=\$SSHHOME
+            echo \"$CMDARG\" >> \$SSHHOME/sshrc.bashrc
             bash --rcfile \$SSHHOME/sshrc.bashrc
             "
     else
@@ -57,9 +65,31 @@ EOF
         exit 1
     fi
 }
-if [ "$1" ]; then
-    command -v openssl >/dev/null 2>&1 || { echo >&2 "sshrc requires openssl to be installed locally, but it's not. Aborting."; exit 1; }
-    sshrc "$@"
-else
-    ssh
-fi
+
+function sshrc_parse() {
+  while [[ -n $1 ]]; do
+    case $1 in
+      -b | -c | -D | -E | -e | -F | -I | -i | -L | -l | -m | -O | -o | -p | -Q | -R | -S | -W | -w )
+        SSHARGS="$SSHARGS $1 $2"; shift ;;
+      -* )
+        SSHARGS="$SSHARGS $1" ;;
+      *)
+        if [ -z "$DOMAIN" ]; then
+         DOMAIN="$1"
+        else
+          local SEMICOLON=$([[ "$@" = *[![:space:]]* ]] && echo '; ')
+          CMDARG="$@$SEMICOLON exit"
+          return;
+        fi
+        ;;
+    esac
+    shift
+  done
+  if [ -z $DOMAIN ]; then
+    ssh || exit 1;
+  fi
+}
+
+command -v openssl >/dev/null 2>&1 || { echo >&2 "sshrc requires openssl to be installed locally, but it's not. Aborting."; exit 1; }
+sshrc_parse "$@"
+sshrc
